import std/[json, strutils, unittest]

import flowcaptain

suite "report":
  test "daily-report scenario produces human-checkable artifacts":
    var a = initCaptainPlan("daily-report", "Daily Report", variant = "A")
    a.nodes.add(node("extract", "Extract", plannedMs = 120))
    a.nodes.add(node("transform", "Transform", plannedMs = 850))
    a.nodes.add(node("publish", "Publish", plannedMs = 90))
    a.edges.add(edge("extract-transform", "extract", "transform"))
    a.edges.add(edge("transform-publish", "transform", "publish"))

    var b = initCaptainPlan("daily-report", "Daily Report", variant = "B")
    b.nodes.add(node("extract", "Extract", plannedMs = 120))
    b.nodes.add(node("transform-a", "Transform A", plannedMs = 430))
    b.nodes.add(node("transform-b", "Transform B", plannedMs = 410))
    b.nodes.add(node("publish", "Publish", plannedMs = 95))
    b.edges.add(edge("extract-a", "extract", "transform-a"))
    b.edges.add(edge("extract-b", "extract", "transform-b"))
    b.edges.add(edge("a-publish", "transform-a", "publish"))
    b.edges.add(edge("b-publish", "transform-b", "publish"))

    let comparison = compare(a.execute().complete(), b.execute().complete())
    let output = artifacts(comparison)
    check output.reportMarkdown.contains("## Executive summary")
    check output.reportMarkdown.contains("## KPI dashboard")
    check output.reportMarkdown.contains("## Decision record")
    check output.reportMarkdown.contains("## Variant scorecard")
    check output.reportMarkdown.contains("## Data quality")
    check output.reportMarkdown.contains("## Overview")
    check output.reportMarkdown.contains("## Flow diagram")
    check output.reportMarkdown.contains("## Structure diagram")
    check output.reportMarkdown.contains("## Timeline")
    check output.reportMarkdown.contains("## Node metrics")
    check output.reportMarkdown.contains("## Edge metrics")
    check output.reportMarkdown.contains("## Improvement impact ranking")
    check output.reportMarkdown.contains("## Operational risk register")
    check output.reportMarkdown.contains("## Bottlenecks")
    check output.reportMarkdown.contains("## Wait insights")
    check output.reportMarkdown.contains("## Parallelism opportunities")
    check output.reportMarkdown.contains("## Failure and retry impact")
    check output.reportMarkdown.contains("## Variant comparison")
    check output.reportMarkdown.contains("## Improvement plan")
    check output.reportMarkdown.contains("## Optimization backlog")
    check output.reportMarkdown.contains("## Trade-offs")
    check output.reportMarkdown.contains("## Next experiment candidates")
    check output.reportMarkdown.contains("## Rollout checklist")
    check output.reportMarkdown.contains("## Evidence")
    check output.reportMarkdown.contains("## FlowSurveyor recommendations")
    check output.reportMarkdown.contains("## Toolkit integration")
    check output.reportMarkdown.contains("FlowDependency nodes")
    check output.reportMarkdown.contains("FlowDependency max fan-in")
    check output.reportMarkdown.contains("FlowDependency density")
    check output.reportMarkdown.contains("FlowWorkRunner batches")
    check output.reportMarkdown.contains("FlowWorkRunner parallelism factor")
    check output.reportMarkdown.contains("FlowGarage artifacts")
    check output.reportMarkdown.contains("FlowLogbook metric density")
    check output.reportMarkdown.contains("FlowLogbook timing coverage")
    check output.reportMarkdown.contains("captain-report.html")
    check output.reportMarkdown.contains("Recommended decision")
    check output.reportMarkdown.contains("Metric density")
    check output.reportMarkdown.contains("Acceptance condition")
    check output.reportMarkdown.contains("Rollback path")
    check output.reportMarkdown.contains("Critical-path share")
    check output.reportMarkdown.contains("Concurrency factor")
    check output.reportMarkdown.contains("Total observed work")
    check output.reportMarkdown.contains("target variant")
    check output.reportMarkdown.contains("transform-b")
    check output.flowMermaid.contains("flowchart LR")
    check output.flowMermaid.contains("n_transform_a")
    check not output.flowMermaid.contains("  transform-a")
    check output.structureMermaid.contains("classDiagram")
    check output.structureMermaid.contains("class n_transform_a")
    check output.structureMermaid.contains("n_transform_a --> n_publish")
    check output.reportHtml.contains("<!doctype html>")
    check output.reportHtml.contains("Execution Flow")
    check output.reportHtml.contains("Arrows")
    check output.reportHtml.contains("transform-b")
    check output.comparisonMermaid.contains("subgraph A")
    let manifest = parseJson(output.manifestJson)
    check manifest["schemaVersion"].getInt() == 1
    check manifest["files"].len == 6
    check manifest["files"][1]["fileName"].getStr() == "captain-report.html"
    check manifest["files"][3]["fileName"].getStr() == "structure.mmd"
    check manifest["files"][5]["byteSize"].getInt() > 0
